### PR TITLE
Updates with a splat to pass ruby 3.0.6

### PR DESCRIPTION
**Pull request by jsonbecker**
Locally, running `rspec` with Ruby 3.0.6 works.

### CODE REVIEW

**Comment by zeisler** [comment]
Thanks for the updates. I’m excited to see my old code still getting used. I’ll see about pushing a new gem version tomorrow.

**Comment by jsonbecker** [comment]
Yeah! We’ve actually moved most of the stack to Elixir and Phoenix, which I suspect you’d like, but we are going through one more season with the legacy application and making sure we’re fully on supported versions.

**Comment by zeisler** [comment]
Elixir seems very cool. I’ve gotten my company to start using Go, nothing shiny, but simple and solid.

**Comment by zeisler** [comment]
Released https://rubygems.org/gems/paper_trail-related_changes/versions/1.0.3

**Pull request merged**
